"""Draft HSI dataset, forward model, and reconstruction schemas."""

from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import Field

from optiresearch.memory.schemas import StrictModel, make_deterministic_id


class HSIDatasetSpec(StrictModel):
    schema_version: str = "0.1-draft"
    dataset_id: str = Field(min_length=1)
    dataset_name: str = Field(min_length=1)
    source: Literal["synthetic", "local", "public_placeholder"]
    dataset_family: Literal["synthetic", "local_npz", "cave", "icvl", "custom"] = "synthetic"
    dataset_path: str | None = None
    normalization: Literal["none", "minmax", "per_band", "global"] = "per_band"
    crop_size: int = Field(default=32, ge=1)
    patch_stride: int = Field(default=32, ge=1)
    max_samples: int | None = Field(default=None, ge=1)
    split_seed: int = 42
    wavelengths_nm: list[float] | None = None
    data_license_note: str | None = None
    spectral_bands: int = Field(ge=1)
    height: int = Field(ge=1)
    width: int = Field(ge=1)
    train_size: int = Field(ge=0)
    val_size: int = Field(ge=0)
    test_size: int = Field(ge=0)
    wavelength_range_nm: tuple[float, float]
    spectral_pattern_type: str = "smooth_low_rank"
    material_count: int = 6
    depth_aware: bool = True
    preprocessing: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)


class HSIForwardModelSpec(StrictModel):
    schema_version: str = "0.1-draft"
    forward_model_id: str = Field(min_length=1)
    optical_artifact_id: Optional[str] = None
    psf_cube_uri: Optional[str] = None
    sensor_type: Literal["mono", "rgb", "hsi", "mock"]
    noise_model: dict[str, Any] = Field(default_factory=dict)
    measurement_type: Literal["single_shot", "multi_shot", "mock"]
    depth_planes: int = Field(ge=1)
    wavelength_bands: int = Field(ge=1)
    forward_mode: Literal["simple_sum", "psf_weighted", "coded_aperture_proxy", "depth_spectral_coded"] = "simple_sum"
    normalize_measurement: bool = True
    preserve_encoder_contrast: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)


class HSIReconstructionSpec(StrictModel):
    schema_version: str = "0.1-draft"
    reconstruction_id: str = Field(min_length=1)
    network_type: Literal["linear_baseline", "optical_conditioned_linear", "tiny_cnn", "unet_tiny", "mock"]
    input_channels: int = Field(ge=1)
    output_bands: int = Field(ge=1)
    loss_terms: list[dict[str, Any]] = Field(default_factory=list)
    train_config: dict[str, Any] = Field(default_factory=dict)
    metric_config: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)


def build_default_synthetic_hsi_dataset_spec(
    spectral_bands: int = 31,
    height: int = 32,
    width: int = 32,
    train_size: int = 16,
    val_size: int = 4,
    test_size: int = 4,
    spectral_pattern_type: str = "mixed_materials",
    material_count: int = 6,
    depth_aware: bool = True,
    wavelengths_nm: list[float] | None = None,
) -> HSIDatasetSpec:
    if wavelengths_nm is not None:
        spectral_bands = len(wavelengths_nm)
    return HSIDatasetSpec(
        dataset_id=make_deterministic_id("hsi_dataset", "synthetic", spectral_bands, height, width, train_size, val_size, test_size),
        dataset_name="synthetic_hsi_v0",
        source="synthetic",
        dataset_family="synthetic",
        dataset_path=None,
        normalization="per_band",
        crop_size=min(32, height, width),
        patch_stride=min(32, height, width),
        wavelengths_nm=wavelengths_nm,
        data_license_note="Synthetic data generated by OptiResearch; not a public or measured HSI dataset.",
        spectral_bands=spectral_bands,
        height=height,
        width=width,
        train_size=train_size,
        val_size=val_size,
        test_size=test_size,
        wavelength_range_nm=(450.0, 700.0),
        spectral_pattern_type=spectral_pattern_type,
        material_count=material_count,
        depth_aware=depth_aware,
        preprocessing={"normalize": "zero_one"},
        metadata={"deterministic": True},
    )


def build_default_hsi_forward_model_spec(
    optical_artifact_id: str | None = None,
    psf_cube_uri: str | None = None,
    depth_planes: int = 9,
    wavelength_bands: int = 31,
    forward_mode: str = "depth_spectral_coded",
) -> HSIForwardModelSpec:
    return HSIForwardModelSpec(
        forward_model_id=make_deterministic_id("hsi_forward", optical_artifact_id, psf_cube_uri, depth_planes, wavelength_bands),
        optical_artifact_id=optical_artifact_id,
        psf_cube_uri=psf_cube_uri,
        sensor_type="mono",
        noise_model={"type": "none"},
        measurement_type="single_shot",
        depth_planes=depth_planes,
        wavelength_bands=wavelength_bands,
        forward_mode=forward_mode,
        normalize_measurement=True,
        preserve_encoder_contrast=True,
        metadata={"model": "spectral_psf_integrating"},
    )


def build_default_hsi_reconstruction_spec(output_bands: int = 31, network_type: str = "optical_conditioned_linear") -> HSIReconstructionSpec:
    train_config = {"fit": "closed_form_scalar_weights"} if network_type == "linear_baseline" else {"fit": "optical_conditioned_least_squares"}
    if network_type in {"tiny_cnn", "unet_tiny"}:
        train_config = {"fit": "optional_torch", "epochs": 5, "device": "cpu"}
    return HSIReconstructionSpec(
        reconstruction_id=make_deterministic_id("hsi_reconstruction", network_type, output_bands),
        network_type=network_type,
        input_channels=1,
        output_bands=output_bands,
        loss_terms=[{"name": "mse", "weight": 1.0}],
        train_config=train_config,
        metric_config={"metrics": ["PSNR", "SSIM", "SAM", "ERGAS"]},
        metadata={"default": True, "use_optical_features": False, "optical_feature_injection": "none"},
    )


def validate_hsi_dataset_spec(spec: HSIDatasetSpec | dict[str, Any]) -> dict[str, Any]:
    """Return structured validation for Phase 11 dataset metadata."""

    try:
        dataset_spec = spec if isinstance(spec, HSIDatasetSpec) else HSIDatasetSpec(**spec)
    except Exception as exc:
        return {"status": "invalid", "error_codes": ["SCHEMA_VALIDATION_FAILED"], "errors": [str(exc)]}

    errors: list[str] = []
    if dataset_spec.crop_size > min(dataset_spec.height, dataset_spec.width) and dataset_spec.crop_size != 32:
        errors.append("CROP_SIZE_EXCEEDS_IMAGE")
    if dataset_spec.patch_stride <= 0:
        errors.append("PATCH_STRIDE_INVALID")
    if dataset_spec.max_samples is not None:
        total = dataset_spec.train_size + dataset_spec.val_size + dataset_spec.test_size
        if dataset_spec.max_samples > max(total, 1):
            errors.append("MAX_SAMPLES_EXCEEDS_DATASET")
    if dataset_spec.wavelengths_nm is not None and len(dataset_spec.wavelengths_nm) != dataset_spec.spectral_bands:
        errors.append("WAVELENGTH_COUNT_MISMATCH")
    if dataset_spec.dataset_family in {"local_npz", "cave", "icvl", "custom"} and not dataset_spec.dataset_path:
        errors.append("DATASET_PATH_REQUIRED")

    return {
        "status": "valid" if not errors else "invalid",
        "error_codes": errors,
        "dataset_id": dataset_spec.dataset_id,
        "dataset_family": dataset_spec.dataset_family,
    }
