"""Phase 26 LLM planner schemas.

Defines the context, proposal, and result types for the LLM-assisted
autonomous research planner.
"""

from __future__ import annotations

from typing import Any, Literal, Optional

from optiresearch.memory.schemas import StrictModel


class LLMPlannerContext(StrictModel):
    """Context passed to the LLM planner for generating research proposals."""

    objective: str
    recent_results: list[dict[str, Any]] = []
    backend_registry_summary: list[dict[str, Any]] = []
    claim_boundaries: list[dict[str, Any]] = []
    research_memory: list[dict[str, Any]] = []
    allowed_backends: list[str] = [
        "phase_to_fft_proxy",
        "deeplens_geolens_geometric",
        "local_synthetic_hsi",
    ]
    allowed_task_types: list[str] = [
        "stable_lens_hsi_codesign",
        "native_hsi_codesign",
        "native_hsi_reconstruction_codesign",
    ]
    execution_mode: Literal["dry_run", "local", "remote_opt_in"] = "dry_run"
    safety_constraints: dict[str, Any] = {}
    max_candidate_plans: int = 3
    metadata: dict[str, Any] = {}


class LLMPlannerProposal(StrictModel):
    """A single research proposal generated by the LLM planner."""

    proposal_id: str = ""
    hypothesis: str = ""
    rationale: str = ""
    recommended_action: str = "stop_and_report"
    backend_id: str = ""
    task_type: str = ""
    objective_profile: Optional[str] = None
    experiment_spec_patch: dict[str, Any] = {}
    expected_evidence_level: Optional[str] = None
    expected_claim_gain: Optional[str] = None
    risk_level: Literal["low", "medium", "high"] = "low"
    required_safety_checks: list[str] = []
    proposed_claim: str = ""
    safe_wording: str = ""


class LLMPlannerResult(StrictModel):
    """Result of an LLM planner run."""

    status: Literal["succeeded", "fallback_used", "failed"]
    provider: str = "mock"
    model: str = "mock-llm"
    planner_run_id: str = ""
    proposals: list[LLMPlannerProposal] = []
    selected_proposal: Optional[LLMPlannerProposal] = None
    rejected_proposals: list[LLMPlannerProposal] = []
    validation_errors: list[dict[str, Any]] = []
    fallback_strategy: Optional[dict[str, Any]] = None
    planner_trace_path: Optional[str] = None
    error: Optional[str] = None
    metadata: dict[str, Any] = {}
